
name: Bare Run on various PHP versions

on: [pull_request, push]
on:
    push:
        tags:
            - '*.72'

jobs:
    bare_run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '7.3', '7.4', '8.0']

        steps:
            -   uses: actions/checkout@v3

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none
            -   run: php bin/monorepo-builder list --ansi
